theme: freelancer-theme
title: Makerswiel Eindhoven
author: Makerswiel Eindhoven
description: Makerswiel is een samenwerkingsverband van vrijwilligersgedreven tech-initiatieven in en om Eindhoven.
