remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Makerswiel Eindhoven
author: Makerswiel Eindhoven
description: Makerswiel is een samenwerkingsverband van vrijwilligersgedreven tech-initiatieven in en om Eindhoven.
show_downloads: false
