remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
title: Makerswiel Eindhoven
author: Makerswiel Eindhoven
description: Makerswiel is een samenwerkingsverband van vrijwilligersgedreven tech-initiatieven in en om Eindhoven.
show_downloads: false

# Add these settings for blog functionality
permalink: /blog/:year/:month/:day/:title
collections:
  posts:
    output: true

# Default layout for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"